CREATE TABLE IF NOT EXISTS "EnergyTransfer" (
    "user_from" UUID NOT NULL UNIQUE,
    "user_to" UUID NOT NULL,
    "community" UUID NOT NULL,
    "energy_Wh" DECIMAL NOT NULL,
    "start" TIMESTAMP NOT NULL,
    "end" TIMESTAMP NOT NULL,
    PRIMARY KEY("user_from")
);

ALTER TABLE "EnergyTransfer"
ADD FOREIGN KEY("user_to") REFERENCES "User"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "EnergyTransfer"
ADD FOREIGN KEY("community") REFERENCES "Community"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "User"
ADD FOREIGN KEY("community") REFERENCES "Community"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "User"
ADD FOREIGN KEY("id") REFERENCES "Manager"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Manager"
ADD FOREIGN KEY("community") REFERENCES "Community"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
