ALTER TABLE "energytransfer"
ADD FOREIGN KEY("user_to") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "energytransfer"
ADD FOREIGN KEY("community") REFERENCES "community"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
ADD FOREIGN KEY("community") REFERENCES "community"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "manager"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "manager"
ADD FOREIGN KEY("community") REFERENCES "community"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
